#!/usr/bin/env sh
set -e

FPM_CONFIG_PATH="${FPM_CONFIG_PATH:-/usr/local/etc/php-fpm.conf}";

FPM_PORT="${FPM_PORT:-9000}";
FPM_USER="${FPM_USER:-root}";
FPM_GROUP="${FPM_GROUP:-root}";

FPM_MAX_CHILDREN="${FPM_MAX_CHILDREN:-20}";
FPM_START_SERVERS="${FPM_START_SERVERS:-9}";
FPM_MIN_SPARE_SERVERS="${FPM_MIN_SPARE_SERVERS:-5}";
FPM_MAX_SPARE_SERVERS="${FPM_MAX_SPARE_SERVERS:-15}";
FPM_MAX_REQUESTS="${FPM_MAX_REQUESTS:-3000}";

sed -i "s#%FPM_PORT%#${FPM_PORT}#g" "$FPM_CONFIG_PATH";
sed -i "s#%FPM_USER%#${FPM_USER}#g" "$FPM_CONFIG_PATH";
sed -i "s#%FPM_GROUP%#${FPM_GROUP}#g" "$FPM_CONFIG_PATH";

sed -i "s#%FPM_MAX_CHILDREN%#${FPM_MAX_CHILDREN}#g" "$FPM_CONFIG_PATH";
sed -i "s#%FPM_START_SERVERS%#${FPM_START_SERVERS}#g" "$FPM_CONFIG_PATH";
sed -i "s#%FPM_MIN_SPARE_SERVERS%#${FPM_MIN_SPARE_SERVERS}#g" "$FPM_CONFIG_PATH";
sed -i "s#%FPM_MAX_SPARE_SERVERS%#${FPM_MAX_SPARE_SERVERS}#g" "$FPM_CONFIG_PATH";
sed -i "s#%FPM_MAX_REQUESTS%#${FPM_MAX_REQUESTS}#g" "$FPM_CONFIG_PATH";

exec "$@";
