FROM postgres:13

RUN apt-get update \
    && apt-get install wget -y \
    && apt-get install postgresql-12-postgis-3 -y \
    && apt-get install sudo -y \
#    && apt-get install postgis -y \ 
   && apt-get install postgis -y \
   && apt-get install php -y

